### ISSUE TITLE
Reproducing Figure 4

### ISSUE THREAD

**Issue by CLemeunier** [mrakotosaon/operatornet#2]
Hi ! 

I would like to reproduce the Figure 4 in the paper.

Is it possible to have more details about the method ? 

Let's say I have : 

- a base mesh S1 with n1 vertices
- a target mesh S2 with n2 vertices
- a functional map C between S1 and S2

I used the function 

```
[D_area, D_conf, D_ext] = compute_diff_operators(S_base, S_target, map, ndim_S, ndim_T)
```

to get D_area and D_ext. 

Let's say I computed 100 eigenvectors / eigenvalues for both shapes, so D_area and D_ext have size 100*100. How can I extract their respective eigenfunctions associated with the largest eigenvalue ? And how can I color code them ?

If I directly extract eigenvectors and eigenvalues from D_ext like that : 

```
[D_ext_evecs, D_ext_evals] = eigs(D_ext, 100, 1e-6);
D_ext_evals = diag(D_ext_evals);
[D_ext_evals, order] = sort(abs(D_ext_evals),'ascend');
D_ext_evecs = D_ext_evecs(:,order);
```

, I can't draw D_ext_evecs(:,end) on S1 like this : 

```
figure();
trisurf(S1.surface.TRIV,S1.surface.VERT(:,1),S1.surface.VERT(:,2),S1.surface.VERT(:,3),D_ext_evecs(:,end))
```

because it doesn't have the right dimension (100x1 instead of n1x1).

In this paper : http://www.lix.polytechnique.fr/~maks/papers/S19_OptPreserve_camera.pdf, in Appendix D, they map the shape difference operator back to the original domain with a formula. Did you use something similar ?

Thanks a lot for your help

**Comment by mrakotosaon** [comment]
Hi @CLemeunier 

To convert the function in the spatial domain you can use:
f = S_base.evecs(:, 1:100)*D_ext_evecs
Where f would be a set of functions on a point cloud. 
Please note that the 'map' variable (which is the point-wise map from target to base) is important here. In Figure 4 we use a perfect map (identity) for illustration. If you map is of low quality/noisy, then the final output can highlight the mismatched area, rather than the semantic meaningful ones. 

Best

**Comment by CLemeunier** [comment]
Ok, thanks for the explanation

After some tests, I can indeed see that using a map different from an identity / perfect one changes the results. I work on meshes that have a different number of vertices, and so the map is not known. So I try to first compute a functional map between the shapes, and then compute the shape difference operator with this functional map.

I have one more question : in the subtitle of the figure, it is said that the first eigenfunction is drawn, but in the article, it is said that the eigenfunction associated with the highest eigenvalue is drawn. So, do I have to draw the first or the last eigenfunction to see the output ? If I draw the last eigenfunction, the size of the functional map will affect the result

Thanks for your time


Edit : I just realised the highest eigenvalue is in fact the first one (we take the absolute value of the eigenvalues). So I assume the eigenfunction to be drawn is the first one ?
